import type { BlendMode, ParamValue } from './types.ts'

export interface PresetLayer {
  effectId: string
  values?: Record<string, ParamValue>
  opacity?: number
  blend?: BlendMode
}

export interface Preset {
  name: string
  layers: PresetLayer[]
}

export const PRESETS: Preset[] = [
  {
    name: 'Cyberpunk',
    layers: [
      { effectId: 'plasma', values: { scale: 8.5, speed: 0.56, shift: 0.95 } },
      { effectId: 'ascii', values: { cellSize: 34, colorize: 0.69, ink: '#90601c' } },
      {
        effectId: 'text',
        values: {
          txt: 'SHADERLAB',
          font: 'Basement Grotesque',
          style: 'Fill + Outline',
          fill: '#ffffff',
          fill2: '#dbdb00',
          grad: 0,
          outCol: '#c712ca',
          size: 0.35,
          posX: 0,
          posY: -0.1,
          rot: 0,
          spin: 0,
          wobble: 0,
          wspeed: 2,
          glitch: 0,
          shadowX: 0.01,
          shadowY: -0.02,
          shadowCol: '#000000',
        },
      },
      {
        effectId: 'text',
        values: {
          txt: 'BLAZE',
          font: 'Zen Dots',
          style: 'Fill',
          fill: '#ffffff',
          fill2: '#ff2d96',
          grad: 0,
          outCol: '#00d5ff',
          size: 0.7,
          posX: 0,
          posY: 0.1,
          rot: 0,
          spin: 0,
          wobble: 0,
          wspeed: 2,
          glitch: 0,
          shadowX: 0.01,
          shadowY: -0.02,
          shadowCol: '#000000',
        },
      },
      { effectId: 'dither', values: { pxSize: 3, levels: 8, spread: 1.94 } },
    ],
  },
  {
    name: 'Waveform',
    layers: [
      {
        effectId: 'flutedglass',
        values: { ribs: 120, refraction: 0.84, curve: 0.056 },
        opacity: 0.03,
      },
      {
        effectId: 'aurora',
        values: {
          colA: '#364695',
          colB: '#442766',
          colC: '#8a1930',
          speed: 1.35,
          intensity: 0.65,
        },
      },
      { effectId: 'bloom', values: { strength: 1.71, cutoff: 0.33, tint: '#15ec8b' } },
      { effectId: 'grain', values: { amount: 0.05, gsize: 1.6 }, opacity: 0.43 },
      { effectId: 'chromab', values: { amount: 2.16, radial: 0.92 } },
    ],
  },
  {
    name: 'Dot Matrix',
    layers: [
      {
        effectId: 'waves',
        values: { colA: '#a14730', colB: '#25caa1', freq: 10, speed: 2, wobble: 2.5 },
        opacity: 0.8,
      },
      {
        effectId: 'halftone',
        values: {
          dotSize: 35,
          colorize: 0.57,
          angle: 0.6,
          ink: '#758336',
          paper: '#fd8937',
        },
      },
      {
        effectId: 'text',
        values: {
          txt: 'BLAZE SHADERLAB',
          font: 'Permanent Marker',
          style: 'Fill',
          fill: '#000000',
          fill2: '#ff2d96',
          grad: 0,
          outCol: '#00d5ff',
          size: 0.8,
          posX: 0,
          posY: 0,
          rot: 0,
          spin: 0,
          wobble: 0.005,
          wspeed: 1.1,
          glitch: 0,
          shadowX: 0.01,
          shadowY: -0.01,
          shadowCol: '#f2f2f2',
        },
      },
      {
        effectId: 'edges',
        values: { strength: 6.5, colorize: 0.28, invert: 0, ink: '#45e9a3' },
      },
    ],
  },
  {
    name: 'Dot Wave',
    layers: [
      {
        effectId: 'waves',
        values: { colA: '#ff3800', colB: '#000000', freq: 10, speed: 1, wobble: 0.75 },
        opacity: 0.8,
      },
      {
        effectId: 'halftone',
        values: {
          dotSize: 35,
          colorize: 0.7,
          angle: 0.4,
          ink: '#ff2f00',
          paper: '#ff4d00',
        },
      },
      {
        effectId: 'text',
        values: {
          txt: 'BLAZE SHADERLAB',
          font: 'Permanent Marker',
          style: 'Fill',
          fill: '#000000',
          fill2: '#ff2d96',
          grad: 0,
          outCol: '#00d5ff',
          size: 0.8,
          posX: 0,
          posY: 0,
          rot: 0,
          spin: 0,
          wobble: 0.005,
          wspeed: 1.1,
          glitch: 0,
          shadowX: 0.01,
          shadowY: -0.01,
          shadowCol: '#8d8b8b',
        },
      },
      {
        effectId: 'edges',
        values: { strength: 20, colorize: 0.8, invert: 0, ink: '#45e9a3' },
      },
    ],
  },
  {
    name: 'Terminal Green CRT',
    layers: [
      {
        effectId: 'noise',
        values: { colA: '#001604', colB: '#2bff71', scale: 7, speed: 0.5, contrast: 1.6 },
      },
      { effectId: 'slice', values: { bands: 40, offset: 0.015, rate: 6 }, opacity: 0.7 },
      { effectId: 'dither', values: { pxSize: 2, levels: 3, spread: 0.8 }, opacity: 0.8 },
      { effectId: 'crt', values: { curvature: 0.7, scanlines: 0.5, rgbMask: 0.15, flicker: 0.06 } },
    ],
  },
  {
    name: 'Molten Kaleido',
    layers: [
      { effectId: 'plasma', values: { scale: 4, speed: 0.4, shift: 0.05 } },
      { effectId: 'kaleido', values: { segments: 6, rotation: -0.15, zoomAmt: 0.9 } },
      { effectId: 'warp', values: { amount: 0.15, scale: 2.5, speed: 0.4 } },
      { effectId: 'posterize', values: { levels: 6, gam: 1.2 } },
      { effectId: 'bloom', values: { strength: 0.5, cutoff: 0.6, tint: '#ffae5c' } },
    ],
  },
  {
    name: 'Warning Tape',
    layers: [
      {
        effectId: 'gradient',
        values: { colA: '#652035', colB: '#a8bd0a', angle: 2.5, scale: 2, speed: 0.5 },
      },
      { effectId: 'ascii', values: { cellSize: 26, colorize: 0.81, ink: '#d7e605' }, opacity: 0.71 },
    ],
  },
  {
    name: 'Silver Surfer',
    layers: [
      { effectId: 'plasma', values: { scale: 4, speed: 2.04, shift: 0.67 } },
      { effectId: 'hueshift', values: { shift: 0.99, animate: 0.74, saturation: 0.03 } },
    ],
  },
  {
    name: 'Wavy Dots',
    layers: [
      {
        effectId: 'waves',
        values: { colA: '#634caa', colB: '#96b128', freq: 32, speed: -1.01, wobble: 1.93 },
      },
      { effectId: 'grain', values: { amount: 0.055, gsize: 1.8 } },
      {
        effectId: 'halftone',
        values: { dotSize: 28, colorize: 0.45, angle: 2.24, ink: '#113d9a', paper: '#1d2431' },
      },
      { effectId: 'grain', values: { amount: 0.02, gsize: 4 } },
    ],
  },
  {
    name: 'Pink Void',
    layers: [
      { effectId: 'plasma', values: { scale: 16.2, speed: 0.7, shift: 0.16 } },
      { effectId: 'grain', values: { amount: 0.115, gsize: 4.4 } },
      {
        effectId: 'threshold',
        values: { cutoff: 0.35, softness: 0.48, dark: '#644984', light: '#ef34fd' },
      },
      { effectId: 'slice', values: { bands: 4, offset: 0.03, rate: 9.6 } },
    ],
  },
  {
    name: 'Aurora Haze',
    layers: [
      {
        effectId: 'waves',
        values: { colA: '#f49df2', colB: '#19c32e', freq: 8.5, speed: -0.49, wobble: 0.02 },
      },
      {
        effectId: 'gradient',
        values: { colA: '#606238', colB: '#6e2c87', angle: 3.71, scale: 0.46, speed: 0.46 },
        opacity: 0.54,
        blend: 'add',
      },
      {
        effectId: 'cosine',
        values: { scale: 1.12, speed: 0.51, shift: 0.52 },
        opacity: 0.57,
        blend: 'multiply',
      },
      { effectId: 'hueshift', values: { shift: 0.06, animate: 0.97, saturation: 0.17 } },
    ],
  },
  {
    name: 'Dystopia',
    layers: [
      {
        effectId: 'truchet',
        values: { colA: '#dffd15', colB: '#0e657f', scale: 5, width: 0.085, rate: 3.7 },
      },
      { effectId: 'ascii', values: { cellSize: 14, colorize: 0.52, ink: '#849f60' } },
      { effectId: 'grain', values: { amount: 0.21, gsize: 2.4 } },
    ],
  },
  {
    name: 'Smoke',
    layers: [
      {
        effectId: 'warp',
        values: { amount: 0.065, scale: 3, speed: 0.4 },
        opacity: 0.9,
      },
      {
        effectId: 'meshgradient',
        values: {
          points: 4,
          col1: '#b5bab7',
          p1x: -0.58,
          p1y: 0.61,
          w1: 2.4,
          col2: '#737373',
          p2x: -0.45,
          p2y: 0.48,
          w2: 1.52,
          col3: '#6c6a6b',
          p3x: 0.75,
          p3y: 0.79,
          w3: 1.47,
          col4: '#e9e9f1',
          p4x: -0.37,
          p4y: -0.18,
          w4: 2.59,
          col5: '#d13e2c',
          p5x: 0.49,
          p5y: 0.17,
          w5: 0.15,
          falloff: 4,
          speedM: 0.95,
          motion: 0.35,
          noiseType: 'Turbulence',
          warpAmt: 0.44,
          warpScale: 0.2,
          warpIter: 4,
          warpDecay: 1.15,
          warpBias: 1,
          seed: 51,
          vortex: -0.9,
          tonemap: 'Reinhard',
          glowStr: 0.8,
          glowThr: 0.3,
        },
      },
      { effectId: 'grain', values: { amount: 0.04, gsize: 2 } },
      {
        effectId: 'threshold',
        values: { cutoff: 0.5, softness: 0.17, dark: '#000000', light: '#ffffff' },
      },
    ],
  },
  {
    name: 'Red Mist',
    layers: [
      {
        effectId: 'starfield',
        values: { tint: '#f75839', colA: '#e26659', density: 49, speed: 0.68, twinkle: 7.4 },
      },
      { effectId: 'grain', values: { amount: 0.12, gsize: 1 } },
      {
        effectId: 'meshgradient',
        values: {
          points: 3,
          col1: '#5586e3',
          p1x: -1.14,
          p1y: 1.14,
          w1: 1.43,
          col2: '#f86e8e',
          p2x: -0.77,
          p2y: 0.3,
          w2: 1.59,
          col3: '#404b0c',
          p3x: -0.91,
          p3y: -0.91,
          w3: 2.97,
          col4: '#279af3',
          p4x: -0.45,
          p4y: -1,
          w4: 0.81,
          col5: '#bc4f64',
          p5x: -0.02,
          p5y: 0.25,
          w5: 0.63,
          falloff: 1.57,
          speedM: 1.31,
          motion: 0.46,
          noiseType: 'Voronoi',
          warpAmt: 0.37,
          warpScale: 3.65,
          warpIter: 5,
          warpDecay: 2.81,
          warpBias: 0.6,
          seed: 31,
          vortex: 0.47,
          tonemap: 'Filmic',
          glowStr: 0.48,
          glowThr: 0.81,
        },
        blend: 'multiply',
      },
    ],
  },
  {
    name: 'Blood Water',
    layers: [
      {
        effectId: 'meshgradient',
        values: {
          points: 4,
          col1: '#5fcdb0',
          p1x: 0.24,
          p1y: 0.03,
          w1: 2.44,
          col2: '#3405bb',
          p2x: 0.7,
          p2y: 0.59,
          w2: 2.07,
          col3: '#d4f75c',
          p3x: -0.83,
          p3y: -0.53,
          w3: 0.95,
          col4: '#dc2261',
          p4x: 0.31,
          p4y: -0.72,
          w4: 2.75,
          col5: '#f38f4a',
          p5x: -0.79,
          p5y: 0.75,
          w5: 1.1,
          falloff: 2.89,
          speedM: 0.83,
          motion: 0.46,
          noiseType: 'Turbulence',
          warpAmt: 0.54,
          warpScale: 3.38,
          warpIter: 3,
          warpDecay: 1.06,
          warpBias: 0.57,
          seed: 2,
          vortex: -0.03,
          tonemap: 'Reinhard',
          glowStr: 0.83,
          glowThr: 0.18,
        },
      },
    ],
  },
  {
    name: 'Instant Nova',
    layers: [
      { effectId: 'plasma', values: { scale: 3.9, speed: 2.3, shift: 0.23 } },
      { effectId: 'grain', values: { amount: 0.355, gsize: 4.2 } },
      {
        effectId: 'starfield',
        values: { tint: '#ec56ad', colA: '#c51841', density: 18, speed: 0.93, twinkle: 7.6 },
        blend: 'multiply',
      },
      {
        effectId: 'meshgradient',
        values: {
          points: 2,
          col1: '#f880ee',
          p1x: -0.45,
          p1y: -0.38,
          w1: 0.58,
          col2: '#5ab79c',
          p2x: -0.08,
          p2y: 0.81,
          w2: 1.14,
          col3: '#bb5e47',
          p3x: -0.7,
          p3y: -0.43,
          w3: 2.12,
          col4: '#1f57fe',
          p4x: -0.69,
          p4y: -0.28,
          w4: 2.59,
          col5: '#2223b6',
          p5x: 0.43,
          p5y: -0.01,
          w5: 0.33,
          falloff: 2.18,
          speedM: 0.28,
          motion: 0.18,
          noiseType: 'Voronoi',
          warpAmt: 0.13,
          warpScale: 1.08,
          warpIter: 2,
          warpDecay: 2.22,
          warpBias: 0.88,
          seed: 46,
          vortex: 0.04,
          tonemap: 'Cinematic',
          glowStr: 0.42,
          glowThr: 0.58,
        },
        blend: 'multiply',
      },
    ],
  },
  {
    name: 'Sand Dune',
    layers: [
      {
        effectId: 'aurora',
        values: { colA: '#add32d', colB: '#f7e1ea', colC: '#dac154', speed: 0.13, intensity: 1.25 },
      },
      {
        effectId: 'pattern',
        values: {
          colA: '#791ddb',
          colB: '#636eae',
          scale: 34,
          speed: 0.6,
          style: 1,
          rotation: 2.5,
        },
        opacity: 0.5047745817881728,
        blend: 'multiply',
      },
      { effectId: 'dither', values: { pxSize: 3, levels: 7, spread: 0.29 } },
      {
        effectId: 'edges',
        values: { strength: 38, colorize: 0.3, invert: 0, ink: '#ab4323' },
      },
    ],
  },
]
